### ISSUE TITLE
Exceptions are swallowed?

### ISSUE THREAD

**Issue by mjmare** [s-cork/Tabulator#39]
I noticed that Exceptions in a headerParams do not surface in the IDE or otherwise. The tabulator just fails.

This is my column def:
```
    def brand_filter_params(cell):    
      raise Exception('O o')
      return {'values': {'cochlear': 'Cochlear', 'oticon': 'Oticon', '': '[]'}} 

:
:

      {'title':"Merk", 'field':"device_brand", 'width': 100, 'sorter':"string", 
       'editor': 'select', 
       'headerFilter':True, 'headerFilterParams': brand_filter_params,
      },
```

Of course initially I had other code in brand_filter_params.

**Comment by s-cork** [comment]
The JavaScript Tabulator library typically doesn't raise exceptions but reports these in the Javascript console. 

There's not much I can do about that. 

Try using the `anvil.js.report_exceptions` decorator for python callbacks sent to JavaScript 

I'll add this to the docs as a suggestion.

There's also a new global option that you might find useful. 

Something like
`anvil.js.report_all_exceptions(True)`

**Comment by s-cork** [comment]
@mjmare  - This is also a problem in Safari
Unlike chrome, safari is reporting all errors as `Script Errors` when thrown in Tabulator.

That left me unable to catch a `ResizeObserverLoop` error that was being unnecessarily reported.
So in Safari you won't see these errors (they do come up in the console but they aren't reported correctly to Anvil by Safari)
If you try chrome you'll see that error is reported correctly.

This is probably something we need to fix in Anvil to do with CORS to make these scripts work properly in Safari.
I'll leave this open to remind me to do that.

_(The decorator solution above will still work)_

**Comment by s-cork** [comment]
Right - some investigation and it appears to be an open bug in Safari:
https://stackoverflow.com/questions/45844565/script-error-errors-in-window-onerror-in-safari-only

I guess this'll get fixed at some point
I'm tempted to turn on: 
`anvil.js.report_all_exceptions(True)` by default

Any thoughts?

**Comment by mjmare** [comment]
Hi Stu,

I still have a puzzling situation with the header filter params function. I'm using Chrome now, and have anvil.js.report_all_exceptions(True) in my startup form.

As before, this is the column def:
```
      {'title':"Merk", 'field':"device_brand", 'width': 100, 'sorter':"string", 
       'editor': 'select', 
       'headerFilter':True, 'headerFilterParams': brand_filter_params,
      },
```

This is the function that returns the header params:
```
    def brand_filter_params(cell):    
#       devices = anvil.server.call('get_devices')
#       devices = set([d['brand'] for d in devices.values()])
#       values = {d.lower():d for d in devices}
#       values['']='--'

      values = {'cochlear': 'Cochlear', 'oticon': 'Oticon', '': '--'}

      values = {'values': values}  
      return values
```
In this form it works fine: it shows a selection list in the Tabulator header filter.
But I want the values to be based on data returned by a server call. See the commented out lines. The commented out code returns a dict identical to the values dict. It does what it should do.

Now the weird part. It does not work in Tabulator: the selection list does not show! No exceptions, no (obvious) errors in the JS console. 
I have traced it down to the anvil.server.call:  if I remove in the code above the comment before the anvil server call this strange behaviour happens. Even if the call result is not used. I'm puzzled.

Any trouble shooting tips?

**Comment by s-cork** [comment]
Yeah. This is an issue with JavaScript not supporting a promise in a callback. 

There should be some docs in anvil on the subject. Look for blocking code in the section on using python callbacks. 

Essentially the server call invokes code that needs to block in python and in JavaScript Tabulator receives a Promise. But in this case JavaScript is not expecting a promise so it just takes the Promise object and uses it rather than awaiting the result from the Promise/server call. 

Tabulator supports Promise in some places - eg in click handlers. Though often it doesn't matter in those sorts of handlers.

**Comment by mjmare** [comment]
In the end it is always Javascript that trips you up ;-) Thanks for your explanation.
For other readers, this is the relevant docs section: https://anvil.works/docs/client/python#blocking-code

BTW do you know why no SuspensionError is raised?

**Comment by s-cork** [comment]
Because we just can't know if a Promise is supported or not. 

It was ultimately a design choice. 

The most common use case for a python callback is a reaction to some JavaScript event. In almost all cases suspensions are fine there because JavaScript doesn't care about the result.

JavaScript says hey this thing happened you do your thing. 

If we always threw a Suspension error then the most common use case wouldn't work. 

In the Tabulator source code I make quite heavy use of Suspensions to Promises especially in the _data_loader module. But it took careful looking at the documentation for Js Tabulator to understand when a Promise was and wasn't supported. 

It would definitely have been better to follow Python's raise an exception. But because that's not the JavaScript way, we had to compromise.

**Comment by mjmare** [comment]
Life is a com-promise.

Thanks again for the explanation.

**Comment by s-cork** [comment]
fyi - i've added support for throwing Suspension Errors in common 'gotcha' places in tabulator
#43

**Comment by mjmare** [comment]
Thanks for "fix". I'm sure it will save people (including future me) some head scratching.
